### ISSUE TITLE
Improve Schema Comparer Error Message

### ISSUE THREAD

**Issue by zeotuan** [mrpowers-io/spark-fast-tests#159]
- [x] Schema Comparer with color diff (#160)
- [x] Schema Comparer should format diff table properly (#160 )
- [x] Schema Comparer support Tree Diff String comparison for large nested schema (#176)
